### ISSUE TITLE
Improving performance of your segpy code

### ISSUE THREAD

**Issue by rob-smallshire** [pareantoine/VSP-Processing#1]
Hi, I'm one of the authors of segpy.  I took a look at your segpy code in `Horizontal_Rotation_Segpy.py` and can offer some advice on how to make it significantly faster.

In this block your *reading* each trace header *four* times:

```
sour_x = np.array([segy_reader.trace_header(trace_index).source_x for trace_index in segy_reader.trace_indexes()])[::3]
sour_y = np.array([segy_reader.trace_header(trace_index).source_y for trace_index in segy_reader.trace_indexes()])[::3]
geo_x = np.array([segy_reader.trace_header(trace_index).group_x for trace_index in segy_reader.trace_indexes()])[::3]
geo_y = np.array([segy_reader.trace_header(trace_index).group_y for trace_index in segy_reader.trace_indexes()])[::3]
```

On my MacBook Pro these four lines take about 120 seconds to execute.

It's important to understand that `segpy` deliberately does not cache any headers or traces in order to allow it to process SEG Y files substantially larger than the available RAM. If you want trace-header caching, you need to implement that yourself.

For example. you could read all the trace-headers once, into a list, and then refer to them many times:

```
# Read all the trace headers once
trace_headers = [segy_reader.trace_header(trace_index)
                 for trace_index in segy_reader.trace_indexes()]

```
This line of code executes in about 44 seconds.

Each of the four lines above also creates an intermediate `list` using a list-comprehension, and then uses the contents of this list to initialise the array. The intermediate list can be avoided by using a generator-expression rather than a list comprehension, and passing the resulting iterator to `numpy.fromiter()`:

```
# extract all source and receiver (geophone) coordinates
sour_x = np.fromiter((trace_header.source_x for trace_header in trace_headers), dtype=np.dtype('i4'), count=len(trace_headers))[::3]
sour_y = np.fromiter((trace_header.source_y for trace_header in trace_headers), dtype=np.dtype('i4'), count=len(trace_headers))[::3]
geo_x = np.fromiter((trace_header.group_x for trace_header in trace_headers), dtype=np.dtype('i4'), count=len(trace_headers))[::3]
geo_y = np.fromiter((trace_header.group_y for trace_header in trace_headers), dtype=np.dtype('i4'), count=len(trace_headers))[::3]
```

It takes less than a second to execute all four of these lines of code.

You can make equivalent changes elsewhere further on in your own code to realise equivalent performance benefits.  As I said previously the `SegYReader` is just that, and it doesn't perform any caching.

**Comment by rob-smallshire** [comment]
If I understand your code correctly, you're only using every third trace header, so there's no need to even load the other two-thirds.

Instead of loading everything then slicing out the bits you want, you can just load the bits you want:

```
# Read every third trace header once
trace_headers = [segy_reader.trace_header(trace_index)
                 for trace_index in islice(segy_reader.trace_indexes(),
                                           None, None, 3)]
```

 Here I'm using `itertools.islice()` to slice every third trace header index, so that is all we load.

On the SEG Y file I'm using here, that brings execution time down to 31 seconds.

**Comment by pareantoine** [comment]
Hi Rob, 

Thanks for all these comments on the code. I actually need sometimes all the headers or every three headers (depends on the data and the function I want to write). 

I wish we could read one specific header but for all traces instead of reading all the headers at once and then selecting the headers we want as in most of the processing I do we only use 4 or 5 headers max out of the long list of SEG-Y rev1 headers available.

Once i've figured out how to load the SEG-Y file efficiently, I'll do some tests though (44 seconds is really not much).

Something that I find puzzling though is how efficient Seisee is at reading all the headers, data and even sorting a SEG-Y file compared to python alternative.
Any comments?

(I'm far from being a professional developer as you can see!)

**Comment by rob-smallshire** [comment]
I don't know much about Seisee, but I expect it's written in C or C++ which are about 10x faster than Python.  We have some proprietary C++ extensions for segpy which make parts of it, such as reading traces in IBM float format, vastly quicker.

**Comment by rob-smallshire** [comment]
Reading just a few headers isn't actually that much quicker than reading them all, due to the way the headers are organised in the SEG Y file.  Even if you just want to read four bytes for a single header, the underlying OS is probably going to read 4096 bytes of the file anyway, so it's no slower just to read the whole header.  That said, you can save memory by only reading a few headers.

Segpy does allow you to do this, by passing the `trace_header_packer` argument to `reader.trace_header()`, although this is an advanced feature which isn't really well documented. Hint:

You can create a subset of the full header containing only the fields you're interested in by using the `SubFormatMeta` metaclass (I told you it was advanced!).  There's an example of creating just such a subset header description in `toolkit.catalog_traces()` called `CatalogSubFormat`. You can then pass the resulting class to the `make_header_packer()` function, which will return a `HeaderPacker` instance which can in turn be passed as the second argument to `reader.trace_header()`. Then, only the fields you're interested in will be extracted.  If you do this, I'd be interested to hear how much faster it is. I would expect it to be faster, as I went to the effort of putting all this machinery in place when I implemented `catalog_traces()`.

**Comment by pareantoine** [comment]
I'll give it a go in the next few days and will let you know.
Obspy for example has the ability to read one single header for all traces as shown in my other codes. And it takes 1 or 2 seconds to read a specific header for the entire SEG-Y. Headers are not loaded in memory and are read straight from SEG-Y file. So maybe the changes you are suggesting will make a difference?

**Comment by rob-smallshire** [comment]
If you're prepared to install the extension package `segpy_numpy`, which is also in the GitHub repo under the `segpy-ext` folder, I've added a new function to `segpy_numpy.extract` called `extract_trace_headers()`.  To it, you can pass a `reader`, a series of trace-header fields or field-names, and an option series of trace-indexes.

With it you can extract multiple headers in one pass into separate numpy arrays. So in your use-case, something like:

```
sour_x, sour_y, geo_x, geo_y = extract_trace_headers(
    reader=segy_reader,
    fields=(TraceHeaderRev0.source_x,
            TraceHeaderRev0.source_y,
            TraceHeaderRev0.group_x,
            TraceHeaderRev0.group_y),
    trace_indexes=islice(segy_reader.trace_indexes(), None, None, 3))
```

This does all the work in one (logical) line of code.  This version builds the index and loads these four headers from my 700 MB file in 8 seconds from fresh.  On subsequent runs it loads these four headers in 2 seconds.  Both a substantial improvement from the 120 seconds we started with!

**Comment by pareantoine** [comment]
Amazing!
Just tried it and it takes 7 seconds to load the 4 headers.
Thanks a lot.
Much easier than me trying to write it!

**Comment by rob-smallshire** [comment]
Excellent news!

**Comment by pareantoine** [comment]
Hi Rob, sorry one more question.
I've been looking at the codes in segpy, and I can't seem to find an option to create a new object Dataset.
For example, if I want to:

1. read a SEG-Y with create_reader 
2. read the headers
3. read the traces
4. modify their values (the traces)
5. create a new Dataset (as in dataset.py) using the headers of the input SEG-Y but the modified traces
6. then write it into a new SEG-Y.

I can't seem to see how this would be done?

**Comment by rob-smallshire** [comment]
Dataset is an abstract base class, so it is just defining what write_segy() function expects, not how to get it.

You need to make a class which inherits from Dataset and overrides all the methods to return the information that will be requested by write_segy().  Notice that a SegYReader is also a dataset, so can probably provide much of what you need.  Into the __init__ of your dataset you will need to pass all the information the Dataset interface needs to expose.

For inspiration there's another example of a Dataset subclass in segpy_numpy.array_dataset.ArrayDataset3d, though it's definitely a work in progress.

**Comment by pareantoine** [comment]
That sounds way out of my league but it could be a good training exercice. I'll have a look into it.
Most of what I'm trying to do is about reading a SEG-Y, modifying headers or samples and writing it as a new SEG-Y. 
Obspy can do that but it's not straight forward at all with lots a small bugs in the writing of SEG-Y files.
I'm hoping Segpy can be a good alternative if I can write this class to be able to go straight from samples and headers into two numpy arrays and then just copying all the others needed information to create a SEG-Y from the input file.

**Comment by rob-smallshire** [comment]
Let me see if I can put a simple example together over the weekend.

**Comment by rob-smallshire** [comment]
I've updated the segpy code on github. There is now a new example called `scaled_samples.py` which simply reads a SEG Y file, multiplies all the sample values by some factor, and writes out the modified SEG Y file. It shows how to subclass the `Dataset` to do this. I've also added a new subclass called `DelegatingDataset` which takes the drudgery out of doing so.  Now you just need to override `__init__()` and, say, `trace_samples()`.  It's pretty straightforward.

**Comment by pareantoine** [comment]
Thanks that will definitely help.
I have to admit that I still don't find that straighforward.
I'm good with writing code with libraries, but I find writing class like this still a bit of a mystery.
I'll give it a go though.

**Comment by pareantoine** [comment]
Hi Rob,

I've had a go at using a class to perform calculation on the input SEG-Y and rotate it.
https://github.com/pareantoine/VSP-Processing/blob/Segpy/Horizontal_Rotation_Segpy.py

The code won't work right now.

In your example code 'scale_samples.sgy' when you call:
transformed_dataset = ScaledSamplesDataset(segy_reader, scale_factor)
Is the code in the class ScaledSamplesDataset run for every trace of the source dataset? I mean all of it is run for each trace?

What I'm trying to achieve in my code is to have  _measure_rotation_angle run only once and save angle_to_rotate as a global variable and then run trace_samples for every trace.
I would also like to be able to use the index of the current trace to output the angle in angle_to_rotate[trace_index].

I guess I'm really lacking experience here. I'm really struggling to see how to do that.

**Comment by pareantoine** [comment]
Hi Rob,

I've updated my rotation and first break picking code. 
Works perfectly now.

Thanks for all your help.

**Comment by rob-smallshire** [comment]
Good to hear! Is the performance okay?

**Comment by pareantoine** [comment]
Yes it's not too bad and I'm not on a powerfull laptop right now.
Saving a SEG-Y file can take a bit of time but that's expected.

**Comment by rob-smallshire** [comment]
If you're dealing with data in IBM format we have a C++ plug-in which can make that substantially faster. Let me know if you're interested.
